version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    commands:
      - echo successfully build 
artifacts:
  files:
    - target/poc-0.0.1-SNAPSHOT.jar app.jar
  discard-paths: yes